### PR TITLE
textarea addition

### PR DESCRIPTION
**Pull request by JohnFordBR**
i mean  wtf  is   socket.on('data', data => {    doing    in  chat  app

      socket.destroy();
  });

### CODE REVIEW

**Comment by fxfactorial** [comment]
@JohnFordBR  What do you mean?

**Comment by JohnFordBR** [comment]
every  time  i try  to delete  it and  send  a  pull request   it says    CONFLICT

**Comment by fxfactorial** [comment]
@JohnFordBR  Read:

https://benmarshall.me/git-rebase/

https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by JohnFordBR** [comment]
so  every  time  you  merge  a  pull  request  i have to do   git rebase  upstream/master ?

**Comment by JohnFordBR** [comment]
is this  pull request right ?

**Comment by JohnFordBR** [comment]
screenshot from 2017-06-02 00-12-09

**Comment by fxfactorial** [comment]
@JohnFordBR Basically, before you start coding, you should rebase from the main copy of the code, which is this repo.

**Pull request merged**
